gravwell/js-client

- package-lock.json
- package.json
> #9 Remove git hooks

- .github/workflows/validate.yml
> Wait for license server

- .github/workflows/npm-publish.yml
- package-lock.json
- package.json
Implements #8 and adds names to `npm-publish` steps
> #8 Grab package version from github release version

- src/models/scheduled-task/to-scheduled-task.ts
> #13 Fix logic that detects if a scheduled task is a script

- .config/tsconfig.node-build.json
- .config/tsconfig.node-spec.json
- package-lock.json
- package.json
- scripts/build.ts
> #49 #15 Export browser typings

- .config/tsconfig.base.json
- .config/tsconfig.browsers-build.json
- .config/tsconfig.browsers-spec.json
- .config/tsconfig.node-build.json
- .config/tsconfig.node-spec.json
- .gitignore
- .prettierignore
- scripts/build.ts
- scripts/test-typescript-compatibility_/.gitignore
> #58 Show tsc error messages on build and point them to src

- .config/tsconfig.base.json
- .config/tsconfig.browsers-build.json
- .config/tsconfig.browsers-spec.json
- .config/tsconfig.node-build.json
- .config/tsconfig.node-spec.json
- scripts/build.ts
> #50 Mimic dist in dist-tsc to emit correct path to source maps

- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-filter.ts
TODO:
- Filter by .desiredGranularity and .fieldFilters
- ~~Remove non-null assertions on `filter.dateRange`~~
- Define default `.desiredGranularity` (is that even possible? @michaelwisely )
> Update SearchFIlter interface to match the GUI

- src/client.spec.ts
- src/functions/actionables/create-one-actionable.spec.ts
- src/functions/actionables/create-one-actionable.ts
- src/functions/actionables/delete-one-actionable.spec.ts
- src/functions/actionables/get-all-actionables.spec.ts
- src/functions/actionables/get-one-actionable.spec.ts
- src/functions/actionables/update-one-actionable.spec.ts
- src/functions/playbooks/create-one-playbook.spec.ts
- src/functions/playbooks/create-one-playbook.ts
- src/functions/playbooks/delete-one-playbook.spec.ts
- src/functions/playbooks/get-all-playbooks-related-to-me.spec.ts
- src/functions/playbooks/get-one-playbook.spec.ts
- src/functions/playbooks/update-one-playbook.spec.ts
- src/functions/templates/create-one-template.spec.ts
- src/functions/templates/create-one-template.ts
- src/functions/templates/delete-one-template.spec.ts
- src/functions/templates/get-all-templates.spec.ts
- src/functions/templates/get-one-template.spec.ts
- src/functions/templates/update-one-template.spec.ts
> #21 Creation handlers should always return the created object 

- src/client.spec.ts
- src/functions/groups/update-one-group.ts
- src/functions/users/update-my-user.ts
- src/functions/users/update-one-user.ts
> #22 Update handlers should return the updated object 

- src/functions/searches/subscribe-to-one-search.spec.ts
> Add a basic test for the raw renderer

- src/functions/searches/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/raw-search-message-received/index.ts
- src/models/search/raw-search-message-sent.ts
- src/models/search/search-stats.ts
- src/value-objects/json.ts
> #101 Return the search metadata on the stats$ observable

- .config/tsconfig.browsers-spec.json
- package-lock.json
- src/client.spec.ts
- src/client.ts
- src/functions/searches/explore-one-tag/explore-one-tag.spec.ts
- src/functions/searches/explore-one-tag/explore-one-tag.ts
- src/functions/searches/explore-one-tag/index.ts
- src/functions/searches/explore-one-tag/initiate-search.ts
- src/models/auto-extractor/raw-auto-extractor-guess.ts
- src/models/auto-extractor/raw-auto-extractor.ts
- src/models/search/data-explorer-entry.ts
- src/models/search/field-filter-operation.ts
- src/models/search/index.ts
- src/models/search/raw-data-explorer-entry.ts
- src/models/search/raw-data-explorer-result.ts
- src/models/search/raw-search-message-received/index.ts
- src/models/search/raw-search-message-received/request-entries-within-range/base.ts
- src/models/search/raw-search-message-received/request-entries-within-range/raw-renderer.ts
- src/models/search/raw-search-message-received/request-entries-within-range/text-renderer.ts
- src/models/search/raw-search-message-sent.ts
- src/models/search/search-filter.ts
- src/models/search/search-message-commands.ts
- src/models/search/to-data-explorer-entry.ts
- src/services/explorer/create-service.ts
- src/services/explorer/index.ts
- src/services/explorer/service.ts
- src/services/index.ts
> #79 Add data explorer messages to search websockets 

- src/functions/searches/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-stats.ts
> #107 -- Add min zoom window to search stats

- src/functions/searches/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-filter.ts
> #114 -- Allow user to specify zoom / overview granularity in search filter

- src/client.spec.ts
- src/functions/searches/stop one-search.ts
- src/functions/searches/stop-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-subscription.ts
- src/services/searches/create-service.ts
- src/services/searches/service.ts
> #78 -- Add stop search functionality

- src/functions/searches/subscribe-to-one-search.spec.ts
- src/models/auto-extractor/to-raw-generatable-auto-extractor.ts
- src/models/search/raw-search-entry.ts
- src/models/search/search-entries.ts
- src/models/search/search-entry.ts
- src/models/search/to-search-entry.ts
> #125 Emit enumerated values with raw/text renderer

- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/raw-search-message-received/index.ts
- src/models/search/raw-search-message-received/request-entries-within-range/base.ts
- src/models/search/raw-search-message-sent.ts
> Correct interface for request entries entry range

- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-stats.ts
- src/models/search/search-subscription.ts
> #134 -- Include query (sent and effective) in the stats overview

- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-stats.ts
- src/models/search/search-subscription.ts
- #134 -- Include query (sent and effective) in the stats overview
> Update before release

- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-stats.ts
> #146 -- Include download formats in search subscription

- src/client.spec.ts
- src/functions/searches/explore-one-tag/explore-one-tag.ts
- src/functions/searches/index.ts
- src/functions/searches/initiate-search.ts
- src/functions/searches/subscribe-to-one-explorer-search/index.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-raw-search.ts
- src/functions/searches/subscribe-to-one-search/helpers.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/explorer-search-subscription.ts
- src/models/search/index.ts
- src/models/search/search-entries.ts
- src/models/search/to-search-entries.ts
- src/services/explorer/create-service.ts
- src/services/explorer/service.ts
- src/services/searches/service.ts
> #140 Add "extended" search subscription that includes explorer elements

- src/functions/system/backup-and-restore.spec.ts
- src/functions/system/backup.ts
- src/functions/system/index.ts
- src/functions/system/restore.ts
- src/services/system/create-service.ts
- src/services/system/service.ts
As of this commit, backup and restore work in the browser, but need some love to work in Node
> #26 - Add backup and restore functionality

- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/explorer-search-subscription.ts
- src/models/search/search-filter.ts
- src/models/search/search-subscription.ts
> #167 -- Add element filters to the SearchFilter interface 

- src/functions/searches/initiate-search.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/raw-search-message-sent.ts
> Add search preview

- src/models/actionable/raw-actionable.ts
- src/models/actionable/to-actionable.ts
> #172 RawActionableCommand.options should always be optional

- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/models/actionable/actionable-command.ts
- src/models/actionable/actionable.ts
- src/models/actionable/index.ts
- src/models/actionable/is-actionable.ts
- src/models/actionable/raw-actionable-command.ts
- src/models/actionable/raw-actionable.ts
- src/models/actionable/to-actionable.ts
- src/models/actionable/to-raw-actionable.ts
> #176 Name individual actionable command interfaces

- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/explorer-search-subscription.ts
- src/models/search/search-subscription.ts
> #182 -- Add method to close the search subscription 

- src/client.spec.ts
- src/functions/auto-extractors/generate-auto-extractors.spec.ts
- src/functions/searches/explore-one-tag/explore-one-tag.ts
- src/functions/searches/initiate-search.ts
- src/functions/searches/stop-one-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-filter.ts
- src/services/explorer/service.ts
- src/services/searches/service.ts
> WIP #186 -- Make date range optional to start a search sub

- src/functions/searches/subscribe-to-one-raw-search.ts
- src/models/search/raw-search-message-sent.ts
> #185 -- PING PONG on search subscriptions

- src/models/auto-extractor/raw-generated-auto-extrators.ts
- src/models/auto-extractor/to-generated-auto-extractor.ts
> Deal with null arrays in generateAutoExtractors()

- src/functions/searches/explore-one-tag/explore-one-tag.spec.ts
- src/functions/searches/explore-one-tag/explore-one-tag.ts
- src/functions/searches/initiate-search.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/explorer-search-subscription.ts
- src/models/search/search-filter.ts
- src/models/search/search-subscription.ts
Requires the latest backend alpha to pass on all tests
> #194 When using preview flag, setting new date range with setFilter not working

- src/functions/searches/modify-one-query.spec.ts
- src/functions/searches/modify-one-query.ts
> #202 -- Throw error if the websocket parse returns a parse error

- src/functions/actionables/update-one-actionable.spec.ts
- src/functions/searches/explore-one-tag/explore-one-tag.ts
- src/functions/searches/initiate-search.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/actionable/actionable-command.ts
- src/models/actionable/actionable.ts
- src/models/actionable/raw-actionable-command.ts
- src/models/actionable/raw-actionable.ts
- src/models/actionable/to-actionable.ts
- src/models/actionable/to-raw-actionable.ts
- src/models/actionable/to-raw-creatable-actionable.ts
- src/models/actionable/to-raw-updatable-actionable.ts
- src/models/search/raw-search-message-sent.ts
- src/services/explorer/service.ts
- src/services/searches/service.ts
> #215 -- Support launching searches without history

- src/client.spec.ts
- src/functions/searches/attach-search.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.spec.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.ts
- src/functions/searches/attach-to-one-search/index.ts
- src/functions/searches/index.ts
- src/functions/searches/subscribe-to-one-search/helpers.ts
- src/models/search/raw-search-message-received/index.ts
- src/models/search/raw-search-message-sent.ts
- src/services/searches/create-service.ts
- src/services/searches/service.ts
> #231 -- Add SearchesService.get.one for existing searches

- .config/test-config/test-backend-alpha/Dockerfile
- .github/workflows/validate-alpha.yml
- .github/workflows/validate-prod.yml
- src/functions/logs/get-log-levels.spec.ts
- src/functions/logs/set-log-level.spec.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.spec.ts
- src/functions/searches/stop-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
> #197 -- Use backend alpha for tests on the dev branch

- src/functions/kits/get-all-archives.ts
Added check on array in response in the test for the get all archives call.
> pr/262 - check on array from response

- src/functions/kits/get-all-archives.ts
Map issue in get archives test
> Map issue in get archives test

- package-lock.json
- package.json
- scripts/test-typescript-compatibility_/run.ts
- src/functions/indexers/get-all-indexers.spec.ts
- src/functions/indexers/get-all-indexers.ts
- src/models/index.ts
- src/models/indexer/assert-is-raw-indexer-response.spec.ts
- src/models/indexer/assert-is-raw-indexer-response.ts
- src/models/indexer/index.ts
- src/models/indexer/indexer-well.ts
- src/models/indexer/raw-indexer-well.ts
- src/models/indexer/raw-replicated-state.ts
- src/models/indexer/raw-shard.ts
- src/models/indexer/raw-well.ts
- src/models/indexer/replicated-state.ts
- src/models/indexer/shard.ts
- src/models/indexer/to-indexer-well.ts
- src/models/indexer/well.ts
- src/services/indexers/create-service.ts
- src/services/indexers/service.ts
Addresses #266
We had to drop support for TS 3.5 and 3.6 to use assertion functions (they were introduced in 3.7)
> #266 -- indexers.get.all()

- src/functions/searches/subscribe-to-one-search/helpers.ts
- src/models/search/search-entries.ts
- src/models/search/to-search-entries.ts
#274 - added numbercard renderer
> #274 - added numbercard renderer 

- src/functions/templates/create-one-template.spec.ts
- src/functions/templates/delete-one-template.spec.ts
- src/functions/templates/get-all-templates.spec.ts
- src/functions/templates/get-one-template.spec.ts
- src/functions/templates/update-one-template.spec.ts
- src/models/template/creatable-template.ts
- src/models/template/is-template.ts
- src/models/template/raw-creatable-template.ts
- src/models/template/raw-template.ts
- src/models/template/raw-updatable-template.ts
- src/models/template/template.ts
- src/models/template/to-raw-creatable-template.ts
- src/models/template/to-raw-updatable-template.ts
- src/models/template/to-template.ts
- src/models/template/updatable-template.ts
Addresses #276
- The new variable type is an array of `TemplateVariable`
- `isRequired` and `previewValue` belongs to the `TemplateVariable` and were removed from the `Template`
> #276 Update the Template interface

- src/functions/system/get-api-version.ts
Adds codename and timezone to the api version call
> Adds codename and timezone to the api version call

- src/models/kit/kit-item.ts
- src/models/kit/raw-kit-item.ts
- src/models/kit/to-kit-item.ts
Auto extractors can be kit items
> (no issue) -- AutoExtractorKitItem

- src/functions/users/create-one-user.spec.ts
- src/functions/users/update-one-user.spec.ts
- src/models/playbook/creatable-playbook.ts
- src/models/playbook/playbook.ts
- src/models/playbook/raw-playbook.ts
- src/models/playbook/to-playbook.ts
- src/models/playbook/to-raw-creatable-playbook.ts
- src/models/playbook/to-raw-updatable-playbook.ts
- src/models/playbook/updatable-playbook.ts
Playbook body is not present if we create a playbook without a body
> Playbook body fix

- src/functions/kits/get-all-archives.ts
- src/models/kit/to-kit-archive.ts
> #295 -- Fix for SchedulesSearches and Scripts on toKitArchive

- src/models/saved-query/raw-updatable-saved-query.ts
- src/models/saved-query/to-raw-updatable-saved-query.ts
> 🐛 #296 toRawUpdatableSavedQuery is missing the user ID

- src/models/dashboard/creatable-dashboard-search.ts
- src/models/dashboard/dashboard-search.ts
- src/models/dashboard/dashboard-tile.ts
- src/models/dashboard/is-dashboard-search.ts
- src/models/dashboard/is-dashboard-tile.ts
- src/models/dashboard/raw-dashboard-search.ts
- src/models/dashboard/raw-dashboard-tile.ts
- src/models/dashboard/raw-dashboard.ts
- src/models/dashboard/raw-updatable-dashboard.ts
- src/models/dashboard/to-dashboard.ts
- src/models/dashboard/to-raw-updatable-dashboard.ts
- Related to this [Gitlab issue](https://kveik.gravwell.io/lucas.paganini/gravgui/-/issues/237) and needed to complete [this PR](https://kveik.gravwell.io/lucas.paganini/gravgui/-/merge_requests/206).
- Besides the renderer options, we noticed that `position.x` and `position.y` can also be `undefined`.
> 🏷️ Add support to legacy dashboards

- src/functions/searches/attach-to-one-search/attach-to-one-search.spec.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.ts
- src/functions/searches/helpers/create-required-search-filter-observable.ts
- src/functions/searches/index.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/functions/searches/tests/index.ts
- src/functions/searches/tests/keep-data-range-test.spec.ts
Addresses #302 
Related to [gitea/origin#4769](https://kveik.gravwell.io/lucas.paganini/gravgui/-/merge_requests/232)
- I thought it was better to abstract this to a maker function since three places are using it. The only thing that I kept outside of the abstraction is the `takeUntil(close$)` that makes more sense to be called within the file where it will be used.
> #302 -- The Search filter is being reset to the initial value

- src/models/actionable/raw-actionable.ts
- src/models/actionable/to-actionable.ts
addresses [295](https://kveik.gravwell.io/lucas.paganini/gravgui/-/issues/295)
> 🐛 Actions and triggers can be nullable

- .config/license-header.json
> Create a docs folder to set as the Github pages source

- src/functions/playbooks/update-one-playbook.spec.ts
- src/models/playbook/creatable-playbook.ts
- src/models/playbook/is-playbook.ts
- src/models/playbook/playbook.ts
- src/models/playbook/raw-playbook-decoded-metadata.ts
- src/models/playbook/to-playbook.ts
- src/models/playbook/to-raw-creatable-playbook.ts
- src/models/playbook/to-raw-updatable-playbook.ts
- src/models/playbook/updatable-playbook.ts
- Commits by @Puszkarek 
- Code review by @LucasPaganini and @iagojsilva
---
Addresses #317. Related to #320.
> #317 -- Missing property for banner on Playbook

- src/models/actionable/to-actionable.ts
- src/value-objects/regex.ts
- src/value-objects/to-regex.spec.ts
`toActionable()` was breaking if the pattern was "pattern"
> Fixes and specs for toActionable()

- src/functions/auto-extractors/create-one-auto-extractor.ts
- src/functions/auto-extractors/update-one-auto-extractor.spec.ts
- src/functions/auto-extractors/update-one-auto-extractor.ts
- src/models/auto-extractor/auto-extractor-modules.ts
- src/models/auto-extractor/is-auto-extractor.ts
- src/models/auto-extractor/raw-auto-extractor.ts
addresses https://github.com/gravwell/js-client/issues/341
> fix(#341) isAutoExtractor does not validate the auto extractor correctly

- src/models/auto-extractor/raw-updatable-auto-extractor.ts
- src/models/auto-extractor/to-raw-updatable-auto-extractor.ts
Addresses #350 
After the PUT request (look at the UID)
Before:
Now:
> fix(#350): Auto extractors is not sending the userID

- src/models/dashboard/creatable-dashboard.ts
- src/models/dashboard/dashboard.ts
- src/models/dashboard/is-dashboard.ts
- src/models/dashboard/raw-creatable-dashboard.ts
- src/models/dashboard/raw-dashboard.ts
- src/models/dashboard/raw-updatable-dashboard.ts
- src/models/dashboard/to-dashboard.ts
- src/models/dashboard/to-raw-creatable-dashboard.ts
- src/models/dashboard/to-raw-updatable-dashboard.ts
- src/models/dashboard/updatable-dashboard.ts
> fix(#353): Dashboard missing the `Global` property

- src/functions/notifications/get-my-notifications.ts
- src/models/notification/notification.ts
> fix(#366): Fix typo on Notification interface

- .github/workflows/validate-alpha.yml
- src/functions/searches/attach-to-one-explorer-search/attach-to-one-explorer-search.spec.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/models/search/raw-search-entry.ts
- src/models/search/search-entry.ts
This PR merges work from `release/v1.0.1` into `dev` via an intermediate merge commit.
> chore: Merge release/v1.0.1 into dev

- src/models/file/to-file-metadata.ts
- src/models/kit/is-config-macro.ts
- src/models/search-module/is-search-module-data.ts
- src/models/search-module/raw-search-module.ts
- src/models/search-module/search-module-data.ts
- src/models/search-module/to-search-module.ts
- src/models/user-preferences/user-preferences.ts
This PR proposes merging `release/v1.1.2` into master in preparation for releasing version `1.1.2`.
> chore: Merge release/v1.1.2 into master

- src/functions/auto-extractors/generate-auto-extractors.spec.ts
- src/functions/searches/attach-to-one-explorer-search/attach-to-one-explorer-search.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/search-entries.ts
- src/models/user-preferences/user-preferences.ts
It proposes merging release/v1.1.3 into master to prepare for the release of version 1.1.3
> chore: Merge release/v1.1.3

- src/client.spec.ts
- src/functions/auto-extractors/get-all-auto-extractor-modules.ts
- src/models/auto-extractor/auto-extractor-data.ts
- src/models/auto-extractor/auto-extractor.ts
- src/models/auto-extractor/creatable-auto-extractor.ts
- src/models/auto-extractor/is-auto-extractor-data.ts
- src/models/auto-extractor/raw-auto-extractor.ts
- src/models/auto-extractor/raw-creatable-auto-extractor.ts
- src/models/auto-extractor/raw-updatable-auto-extractor.ts
- src/models/auto-extractor/updatable-auto-extractor.ts
- src/models/kit/kit-item.ts
- src/models/kit/raw-kit-item.ts
- src/services/auto-extractors/service.ts
- src/value-objects/date.ts
It proposes merging release/v2.0.5 into main to prepare for the release of version 2.0.5.
>  chore: Merge release/2.0.5 to main

- src/functions/searches/modify-one-query.spec.ts
- src/models/user-preferences/user-preferences.ts
It proposes merging release/2.2.0 into main to prepare for the release of version 2.2.0.
>  chore: Merge release/2.2.0 to main
