gravwell/js-client

- .github/workflows/validate.yml
Don't use a `while` loop -- if there's a docker problem (or whatever) and the license server doesn't stand up, we end up spending compute power doing nothing.
Use an `until` that counts up to 5 tries, why not.
Fixes #53
> Use limited number of retries in validate action

- package-lock.json
- package.json
- src/functions/searches/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/raw-search-message-received/request-entries-within-range/index.ts
- src/models/search/raw-search-message-received/request-entries-within-range/text-renderer.ts
- src/models/search/search-entries.ts
- src/models/search/to-search-entries.ts
- src/tests/utils.ts
Addresses #63 
Use the `renderModule` from the backend to choose which normalizer function to use on search entries.
> fix/63 -- Use renderModule from backend message to normalize search entries

- .github/workflows/validate.yml
Browser tests are not ready and are turning our CI checks into noise.
> Validate browser tests setup but don't run the actual tests for now

- src/functions/auto-extractors/generate-auto-extractors.spec.ts
- src/models/auto-extractor/generated-auto-extractors.ts
- src/models/auto-extractor/raw-generated-auto-extrators.ts
- src/models/auto-extractor/to-generated-auto-extractor.ts
Addresses #112 
The confidence scores aren't available in 4.1.3, so I've got some checks for undefined in the test for now. When 4.1.4 hits, we can remove those.
> #112 - Add confidence score to generated AX's

- src/functions/searches/initiate-search.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
- src/models/search/explorer-search-subscription.ts
- src/models/search/raw-search-message-received/index.ts
- src/models/search/search-message-commands.ts
- src/models/search/search-subscription.ts
This is toward #165, but it's not a complete solution for #165.
This PR tests that we're bailing out when we receive an `Error` in search initialization.
> #165 -- Test / handle invalid queries

- src/functions/utils/parse-json-response.ts
The API to update the password returns an error string, and not a JSON object so adding code to handle a situation like this so we don't have to wait for the backend to update.
> Handling of string error message

- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.ts
If one performs a long-running search, the client may receive a response with partial results for search entries or search stats. This PR adds polling logic, so that the search subscription will continue to emit entry/stat values until their respecitive `Finished` flag is set to true.
If `setFilter` is called before a long-running search is complete, polling is stopped and started again after filters are applied.
> Add logic to poll until search is finished

- src/functions/dashboards/create-one-dashboard.spec.ts
- src/functions/dashboards/delete-one-dashboard.spec.ts
- src/functions/dashboards/get-all-dashboards.spec.ts
- src/functions/dashboards/get-dashboards-authorized-to-me.spec.ts
- src/functions/dashboards/get-dashboards-by-group.spec.ts
- src/functions/dashboards/get-dashboards-by-user.spec.ts
- src/functions/dashboards/get-one-dashboard.spec.ts
- src/functions/dashboards/update-one-dashboard.spec.ts
- src/functions/saved-queries/update-one-saved-query.spec.ts
- src/models/timeframe/is-timeframe.ts
- src/models/timeframe/raw-timeframe.ts
- src/models/timeframe/timeframe.ts
- src/models/timeframe/to-raw-timeframe.ts
- src/models/timeframe/to-timeframe.ts
The possible states of the `defaultTimeframe` attribute of a SavedQuery wasn't fully modeled in the RawTimeframe+Timeframe types and related functions (toTimeframe, isTimeframe).
RawTImeframe+Timeframe:
* timezone attribute added.
* durationString, timeframe, and timezone may be null/undefined.
> Modify Timeframe types, account for possible Metadata states of `SavedQuery`s

- src/functions/utils/type-guards.ts
- src/models/search/raw-search-message-received/request-entries-within-range/raw-renderer.ts
- src/models/search/raw-search-message-received/request-entries-within-range/text-renderer.ts
- src/models/search/search-entries.ts
We were dropping the `Tags` field coming from `ID:18`'s for the `raw` and `text` renderers.
This PR keeps the tags field, because we need it to do proper tag ID lookups.
> Add tags fields for raw/text renderers

- src/functions/playbooks/create-one-playbook.spec.ts
- src/functions/playbooks/update-one-playbook.spec.ts
- src/models/playbook/creatable-playbook.ts
- src/models/playbook/raw-creatable-playbook.ts
- src/models/playbook/raw-updatable-playbook.ts
- src/models/playbook/to-raw-creatable-playbook.ts
- src/models/playbook/to-raw-updatable-playbook.ts
- src/models/playbook/updatable-playbook.ts
The `CreatablePlaybook` and `UpdatablePlaybook` interfaces were missing the `author` property.
> fix(#326): CreatablePlaybook and UpdatablePlaybook is missing author property

- src/models/playbook/is-playbook.ts
Adresses: [#330](https://github.com/gravwell/js-client/issues/330)
To test if it was working correctly, I wrote the following code:
Before the implementation, it falls to the `it is not a playbook` case:
After the implementation, it falls to the `it is a playbook` case:
> fix(#330): The `playbook.name` can be null but we don't validate that on the `isPlaybook` method

- .config/test-config/test-backend-alpha/Dockerfile
- src/functions/search-groups/update-one-user-search-group.ts
- src/functions/searches/modify-one-query.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/templates/create-one-template.ts
- src/models/token/token-capability.ts
Adresses: [#336](https://github.com/gravwell/js-client/issues/336)
Important to say that, the issue was even bigger than what was described on `gitea`, so when any template was created, an 400 request was received and didn't go to `/templates` page after clicking on the save button. (And probably that's why drone was failing on template tests)
https://user-images.githubusercontent.com/69917459/173917689-1683d244-677f-4625-9dab-7c1405c393b2.mp4
With the current solution, beyond the fact, that the template is working, and the drone will probably be fixed, now we do one request (create one template) to the back-end instead of two (create one template and get one template).
After the implementation, here is the behavior on the template page (add, edit and delete works correctly): …
> fix(#336): Can't fetch a template just after creation.

- .config/test-config/test-backend-alpha/Dockerfile
- src/functions/templates/create-one-template.ts
Months ago, gravwell started to serve the backend alpha in a different domain, `gin.gravwell.io`. But JSClient is using the old one `update.gravwell.io`
This PR replaces the old URLs with the new ones.
> #(no-issue): Update gravwell alpha backend URLs in `Dockerfile`

- src/functions/auto-extractors/is-valid-auto-extractor-syntax.ts
Addresses https://github.com/gravwell/js-client/issues/343
The makeIsValidAutoExtractorSyntax function was using the wrong API endpoint. This PR corrects this mistaken endpoint.
> fix(#343): Replace the `templatePath` to `/api/autoextractors/test`

- src/functions/searches/subscribe-to-query-parsing.ts
- src/models/search/element-filter.ts
- src/models/search/raw-element-filter.ts
- src/models/search/to-element-filter.ts
There are really two forms of element filters.
1. Operation filters (what's solely been implemented before this PR) that can be used to update a query to perform some operation
2. Extraction filters that can be used to update a query to extract a field (may help to "build up" a query using DE).
This PR has implemented the second. Original element filter types are now union types of one and two.
> frontend issues 3287: Add support for extraction element filters.

- src/models/scheduled-task/is-scheduled-task-base.ts
- src/models/scheduled-task/raw-scheduled-task.ts
- src/models/scheduled-task/scheduled-query-data.ts
- src/models/scheduled-task/scheduled-task-base.ts
- src/models/scheduled-task/to-raw-creatable-scheduled-task.ts
- src/models/scheduled-task/to-scheduled-task-base.ts
Addresses: #372, gravwell/frontend-issues#5339
- Always that we don't have the last run the backend returns the `LastRun` property with the value = `'0001-01-01T00:00:00Z'`, so to make that easier to understand, always that the LastRun value be the same as the `'0001-01-01T00:00:00Z'` we will return `null` instead
- `RawScheduledTask` has the optional properties `LastRun` and `LastRunDuration`, but since we don't have a reason to have these properties separate, we create a new property in the `ScheduledTask` interface that has both:
```
lastRun: {
date: raw.LastRun;
duration: raw.LastRunDuration;
}
```
> Fix(#372): Fix the ScheduledTask types

- .github/workflows/validate-alpha.yml
- src/functions/searches/attach-to-one-explorer-search/attach-to-one-explorer-search.spec.ts
- src/functions/searches/attach-to-one-search/attach-to-one-search.spec.ts
- src/functions/searches/subscribe-to-one-explorer-search/subscribe-to-one-explorer-search.spec.ts
- src/functions/searches/subscribe-to-one-search/subscribe-to-one-search.spec.ts
- src/models/search/raw-search-entry.ts
- src/models/search/search-entry.ts
ipfix data within Data Explorer may have null `data` fields. SearchEntry and related types/functions have been updated to account for this.
> Fix(frontend issue 5359): SearchEntry's `data` field may be null.

- .github/workflows/npm-publish.yml
The versions of node / NPM used by `npm-publish` were way behind the versions used in other workflows. This PR updates the versions to match.
> ci: Bump Node/NPM versions

- src/functions/searches/modify-one-query.spec.ts
It proposes making a change to match a changed backend query-rewriting behavior.
> Update test to match new backend behavior

- .github/workflows/validate-prod.yml
- CONTRIBUTING.md
It proposes updating source to account for the `master` -> `main` branch rename.
> chore: Update branch name

- .config/test-config/test-backend-alpha/Dockerfile
This PR proposes changing a couple URLs to fix an issue where CI can't `apt install` the Gravwell backend.
> ci: Update Dockerfile to use new alpha package host
